### ISSUE TITLE
no Ping

### ISSUE THREAD

**Issue by Jonathan-GC** [EMnify/doc#3]
I have my credentials de enmify and somethings clients, but I have a problem, my pc in windows and Centos7 doesn't ping at  enmify clients.    

my file .ovpn is:

```
client
dev tun
proto udp
remote us-east-1.openvpn.emnify.net 1194
resolv-retry infinite
nobind
explicit-exit-notify 3
keepalive 1 5
user root
group nobody
;persist-key
persist-tun
ns-cert-type server
verb 3
;auth-nocache
auth-user-pass "D:\\Desktop\\openVPN\\credentials.txt"
auth-retry nointeract
....
```

C:\>ping 100.81.0.4

Haciendo ping a 100.81.0.4 con 32 bytes de datos:
Respuesta desde 10.80.119.9: Host de destino inaccesible.
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.

Estadísticas de ping para 100.81.0.4:
    Paquetes: enviados = 4, recibidos = 1, perdidos = 3

**Comment by StephenKing** [comment]
Dear @45duro,

Please double-check that you use a service profile with the `us-east-1 (VPN)` breakout.

I suggest to reach out to `supportATemnify.com`, if this doesn't help.

As customer support is handled via our ticketing system, I would close this issue here. Our support team isn't monitoring this issue tracker.

Thanks for understanding
Steffen
